# Generated by Django 4.1.1 on 2022-09-16 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('expiration_date', models.DateField()),
                ('drink_choice', models.CharField(choices=[('A', 'Alcoholic'), ('S', 'Soft'), ('T', 'Tonicdrink')], max_length=1)),
            ],
        ),
    ]
