# Generated by Django 4.1.1 on 2022-09-14 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='school_type',
            field=models.CharField(choices=[('private_school', 'Private_school'), ('state_school', 'State_school')], default=1, max_length=30),
            preserve_default=False,
        ),
    ]
